---
title: "R Notebook"
output: html_notebook
---


```{r}
library(readxl)
library(tidyverse)
library(dplyr)
library(tidytext)

list_of_files <- list.files(path = "out",
                            recursive = TRUE,
                            pattern = "\\.csv$",
                            full.names = TRUE)
df <- list_of_files %>%
    set_names() %>% 
    map_df(read_csv, .id = "file_name")
```


```{r}
spec(df)
```

```{r}
library(stringr)
string = "Hello world!"

# escape character "
string = "Hello \"world\"!"
writeLines(string)

# escape character \
string = "<em>Hello world!<\\em>"
writeLines(string)

# a vector of strings
s = c("Hello", "world", "!")
s

# string length
str_length("Hello")
str_length(s)

# combining strings
str_c("Hello", "world!")
str_c("Hello", "world!", sep=" ")

# vectorized
str_c(c("1", "2", "3"), c("a", "b", "c"))
str_c("prefix-", c("a", "b", "c"), "-suffix")

# sorting
# Default locale
stringi::stri_locale_info()
str_sort(letters)
str_order(letters)

# Hawaiian
str_sort(letters, locale = "haw")
str_order(letters, locale = "haw")
```


```{r}
df2 = unnest_tokens(tbl = df, output = word, input = text)%>%
  anti_join(stop_words)

df2 %>%
  count(word, sort = TRUE)
```


```{r}
df2["tag"] = substr(df2["file_name"],4,10) 
df2
```


```{r}
get_sentiments("bing")
get_sentiments("afinn")
get_sentiments("nrc")


nrc_joy <- get_sentiments("nrc") %>% 
  filter(sentiment == "joy")

df2 %>%
  inner_join(nrc_joy) %>%
  count(word, sort = TRUE)
```
```{r}
df2 %>%
  inner_join(get_sentiments("bing")) %>%
  count(word, sentiment, sort = TRUE) %>%
  ungroup()
```


```{r}

df2 %>%
  inner_join(get_sentiments("bing")) %>%
  count(word, sentiment, sort = TRUE) %>%
  ungroup() %>%
  group_by(sentiment) %>%
  top_n(10) %>%
  ungroup() %>%
  mutate(word = reorder(word, n)) %>%
  ggplot(aes(word, n, fill = sentiment)) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~sentiment, scales = "free_y") +
  labs(y = "Contribution to sentiment",
       x = NULL) +
  coord_flip()
```


```{r}
bingnegative <- get_sentiments("bing") %>% 
  filter(sentiment == "negative")

wordcounts <- df2 %>%
  group_by(title) %>%
  summarize(words = n())

df2 %>%
  semi_join(bingnegative) %>%
  group_by(title) %>%
  summarize(negativewords = n()) %>%
  left_join(wordcounts, by = c("title")) %>%
  mutate(ratio = negativewords/words) %>%
  group_by(title) %>% 
  top_n(1, ratio) %>%
  ungroup()
```


```{r}

df2 %>%
  count(word) %>%
  inner_join(get_sentiments("loughran"), by = "word") %>%
  group_by(sentiment) %>%
  top_n(5, n) %>%
  ungroup() %>%
  # reorder treats its first argument as a categorical variable, and reorders its levels based on the values of a second variable
  mutate(word = reorder(word, n)) %>%
  ggplot(aes(word, n)) +
  geom_col() +
  coord_flip() +
  facet_wrap(~ sentiment, scales = "free") +
  ylab("Frequency of this word in the recent financial articles")
```


```{r}
stock_sentiment_count <- df2 %>%
  inner_join(get_sentiments("loughran"), by = "word") %>%
  count(sentiment, file_name) %>%
  spread(sentiment, n, fill = 0)

stock_sentiment_count

```


```{r}
stock_sentiment_count %>%
  # positive score normalized by number of words
  mutate(score = (positive - negative) / (positive + negative)) %>%
  mutate(file_name = reorder(file_name, score)) %>%
  ggplot(aes(file_name, score, fill = score > 0)) +
  geom_col(show.legend = FALSE) +
  coord_flip() +
  labs(x = "Company",
       y = "Positivity score among 20 news articles")
```


```{r}



book_words <- df2 %>%
  count(file_name, word, sort = TRUE) %>%
  ungroup()

total_words <- book_words %>% 
  group_by(file_name) %>% 
  summarize(total = sum(n))

book_words <- 
  left_join(book_words, total_words)

# term frequency distribution
ggplot(book_words, aes(n / total, fill = file_name)) +
  geom_histogram(show.legend = FALSE) +
  # You can leave one value as NA to compute from the range of the data.
  xlim(NA, 0.0009) +
  facet_wrap(~file_name, ncol = 2, scales = "free_y")
```


```{r}
freq_by_rank <- book_words  %>% 
  group_by(word) %>% 
  mutate(rank = row_number(), 
         `term frequency` = n/total)

freq_by_rank

freq_by_rank %>% 
  ggplot(aes(rank, `term frequency`, group = file_name, color = file_name)) + 
  geom_line(size = 1.1, alpha = 0.8, show.legend = FALSE) + 
  scale_x_log10() +
  scale_y_log10()
```


```{r}

book_words <- book_words %>%
  bind_tf_idf(word, file_name, n)
book_words

book_words %>%
  select(-total) %>%
  arrange(desc(tf_idf))

book_words %>%
  arrange(desc(tf_idf)) %>%
  group_by(file_name) %>% 
  top_n(15, tf_idf) %>% 
  ungroup %>%
  mutate(word = reorder(word, tf_idf)) %>%
  ggplot(aes(word, tf_idf, fill = file_name)) +
  geom_col(show.legend = FALSE) +
  labs(x = NULL, y = "tf-idf") +
  facet_wrap(~file_name, ncol = 2, scales = "free") +
  coord_flip()

```


```{r}

df3 <- df %>%
  unnest_tokens(bigram, text, token = "ngrams", n = 2) %>% 
  filter(!is.na(bigram))
df3

df3 %>%
  count(bigram, sort = TRUE)
```


```{r}

bigrams_separated <- df3 %>%
  separate(bigram, c("word1", "word2"), sep = " ")

bigrams_filtered <- bigrams_separated %>%
  filter(!word1 %in% stop_words$word) %>%
  filter(!word2 %in% stop_words$word)

# new bigram counts
bigram_counts <- bigrams_filtered %>% 
  count(word1, word2, sort = TRUE)

bigram_counts
```


```{r}

bigrams_united <- bigrams_filtered %>%
  unite(bigram, word1, word2, sep = " ")

bigrams_united
```


```{r}
df %>%
  unnest_tokens(trigram, text, token = "ngrams", n = 3) %>%
  filter(!is.na(trigram)) %>% 
  separate(trigram, c("word1", "word2", "word3"), sep = " ") %>%
  filter(!word1 %in% stop_words$word,
         !word2 %in% stop_words$word,
         !word3 %in% stop_words$word) %>%
  count(word1, word2, word3, sort = TRUE)
```


```{r}

bigram_tf_idf <- bigrams_united %>%
  count(file_name, bigram) %>%
  bind_tf_idf(bigram, file_name, n) %>%
  arrange(desc(tf_idf))

bigram_tf_idf
```


```{r}

bigram_tf_idf %>%
  arrange(desc(tf_idf)) %>%
  group_by(file_name) %>%
  top_n(12, tf_idf) %>%
  ungroup() %>%
  mutate(bigram = reorder(bigram, tf_idf)) %>%
  ggplot(aes(bigram, tf_idf, fill = file_name)) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~ file_name, ncol = 2, scales = "free") +
  coord_flip() +
  labs(y = "tf-idf of bigram to novel",
       x = "")
```


```{r}

bigrams_separated %>%
  filter(word1 == "not") %>%
  count(word1, word2, sort = TRUE)

AFINN <- get_sentiments("afinn")

not_words <- bigrams_separated %>%
  filter(word1 == "not") %>%
  inner_join(AFINN, by = c("word2" = "word")) %>%
  count(word2, value, sort = TRUE)

not_words

```


```{r}

not_words %>%
  mutate(contribution = n * value) %>%
  arrange(desc(abs(contribution))) %>%
  head(20) %>%
  mutate(word2 = reorder(word2, contribution)) %>%
  ggplot(aes(word2, n * value, fill = n * value > 0)) +
  geom_col(show.legend = FALSE) +
  xlab("Words preceded by \"not\"") +
  ylab("Sentiment value * number of occurrences") +
  coord_flip()

```


```{r}
library(igraph)
library(tidygraph)
library(ggraph)

bigram_graph <- bigram_counts %>%
  filter(n > 20) %>% 
  as_tbl_graph()

bigram_graph

```


```{r}
a <- grid::arrow(type = "closed", length = unit(.1, "inches"))

# plot the graph
ggraph(bigram_graph, layout = "fr") +
  geom_edge_link(aes(edge_alpha = n), show.legend = FALSE,
                 arrow = a, end_cap = circle(.07, 'inches')) +
  geom_node_point(color = "lightblue", size = 1) +
  geom_node_text(aes(label = name), vjust = 1, hjust = 1) +
  theme_void()
```


```{r}
library(widyr)

# separate words in sections (10 lines)
austen_section_words <- df2 %>%
  filter(!(word %in% stop_words$word))

austen_section_words

# count words co-occuring within sections
word_pairs <- austen_section_words %>%
  pairwise_count(word, file_name, sort = TRUE)

word_pairs

```

